version: '3.8'
services:
  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: secretroot
      MYSQL_DATABASE: timetracker
      MYSQL_USER: ttuser
      MYSQL_PASSWORD: ttpassword
    ports:
      - 3306:3306
  redis:
    image: redis:6.0.8-alpine3.12
    ports:
      - 6379:6379
